### ISSUE TITLE
Abstraction socket TCP messaging

### ISSUE THREAD

**Issue by aberba** [shove70/buffer#2]
The current implementation is really awesome but using it is still verbose. Having to use TCP directly and bytes is feels too low level for everyday usage.

Would be much convenient when the details are abstracted into an event-based approach for handle connection and sending messages (if you're familiar with Socket.IO in JavaScript).

```d
server.on("connection", &handlerConnection);
server.on("call", &handleCall)

server.bindTCP("127.0.0.1", 8080)
//or
serverSettings = new ServerSettings()
server settings.setCliet(new TCPClient())// or any other UDP, etc
```

Client could also be abstracted this way. Buffer is a very useful to me cus I'm into microservices

**Comment by shove70** [comment]
Thank you for your advice. I'll think about it seriously.

**Comment by aberba** [comment]
Thanks.  With event names,  since D has `enum` its much safer (prevent typo)  to do

```d
server.on(Event.connection, ...) 
```

**Comment by shove70** [comment]
OK, that's a good idea.  :)

**Comment by aberba** [comment]
What happened?

**Comment by shove70** [comment]
Sorry, misoperation, I reopened it.
