### ISSUE TITLE
server example does not compile

### ISSUE THREAD

**Issue by dangbinghoo** [shove70/buffer#3]
`Compiling script: message LoginInfo { string name; string password; ...
../../.dub/packages/buffer-0.2.7/buffer/libbuffer/src/buffer/rpc/server.d-mixin-55(66,33): Error: incompatible types for (ret) is (null): long and typeof(null)
source/app.d(80,46): Error: template instance `buffer.rpc.server.Server!(Business).Server.Handler!null` error instantiating
/usr/bin/dmd failed with exit code 1.`

it seems that long type in the following code doesn't mixing.

```
long GetUserId(string name)
    {
        // Access the database, query the user's id by name, assuming the user's ID is 1
        int userId = 1;
        // ...
        // Query OK.
        
        return userId;
    }
```

and my D compiler version is 2.083.0, ldc 1.20.0 

Thanks!

**Comment by shove70** [comment]
Thanks very much.
This bug has been repaired.
