### ISSUE TITLE
design mistake: client call param count limit is incorrect.

### ISSUE THREAD

**Issue by dangbinghoo** [shove70/buffer#4]
hi,

I think there's some design mistake with the Client code implementation.

if I have a such a message:

```
    message WebReqRetInfo {
        int32 status;
        string info;
    }
```
Yes, this is actually the **Ret** object prototype. not the **Input** one. 
But when compiling this code

```
Client.call!WebReqRetInfo("webRequest", "recfg");
```
we got err:

```
.dub/packages/buffer-0.2.7/buffer/libbuffer/src/buffer/rpc/client.d(44,13): Error: static assert:  "Incorrect number of parameters, WebReqRetInfo requires 2 parameters."
source/rpcClient.d(38,37):        instantiated from here: call!(WebReqRetInfo, string)
/usr/bin/dmd failed with exit code 1
```
which says that I need to put 2 parameters for the "webRequest" call. 
this is something I think that parameter limit the **Return** incorrectlly applied to the **Input**, there's nothing telling this in the `message` prototype.

Thanks!

**Comment by shove70** [comment]
Hello,

When the prototype defines two parameters, you must pass in three parameters when calling:
Client. call! WebReqRetInfo ("method name", first parameter, second parameter);

message WebReqRetInfo {
    int32 status;
    string info;
}

Client.call!WebReqRetInfo("webRequest", status, info);  // webRequest is the method name in the server.
